export const ERROR_CODES = {
  SCAN_FAILED: 'SCAN_FAILED',
  BUILD_FAILED: 'BUILD_FAILED',
  INVALID_IMAGE: 'INVALID_IMAGE',
  QUEUE_FULL: 'QUEUE_FULL',
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
